neo4j_credentials:
  NEO4J_URI: bolt://192.168.1.146:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password
  NEO4J_DB: neo4j

shepherd:
  OVERWRITE_PREPROCESSED_DATA: True
  LIMIT_SAMPLE_SIZE: True
  NUMBER_OF_SAMPLES_LIMIT: 10
  ONLY_PATIENTS_WITH_DISEASE: False

  CREATE_SPL_MATRIX: False

  RUN_PATIENTS_LIKE_ME: True
  RUN_CAUSAL_GENE_DISCOVERY: True
  RUN_DISEASE_CATEGORIZATION: True

  PATIENTS_AGGR_NODES: phenotypes

  RUN_PREPROCESSING: False
  RUN_TRAINING_DISEASE_CHARACTERIZATION: False
