neo4j_credentials:
  NEO4J_URI: neo4j://localhost:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password
  NEO4J_DB: neo4j

shepherd:
  RUN_PRETRAINING: False
  USE_HAUNER_GRAPH: True
  USE_SIMULATED_PATIENTS: True

  OVERWRITE_PREPROCESSED_DATA: False # If True, the patients data will be pulled from the neo4j database
  LIMIT_SAMPLE_SIZE: False 
  NUMBER_OF_SAMPLES_LIMIT: 10
  ONLY_PATIENTS_WITH_DISEASE: False # If True, only patients with disease will be used. If during mapping from DOID to MONDO, no diseases are found, the patient will be excluded.
  ONLY_PATIENTS_WITH_PHENOTYPES: True 
  ONLY_PATIENTS_WITH_GENES: True

  CREATE_SPL_MATRIX: False # This is necessary if the algo is run on new data

  # this runs the predictions
  RUN_PATIENTS_LIKE_ME: False
  RUN_CAUSAL_GENE_DISCOVERY: False
  RUN_DISEASE_CATEGORIZATION: False

  PATIENTS_AGGR_NODES: phenotypes # Options: phenotypes, phenotypes_and_genes - for patients like me and disease categorization the aggregation for the patient embedding can be changed

  MOVE_RESULTS_TO_OUTPUT_DIR: False # This moves the results to the output directory after every prediction

  RUN_PREPROCESSING: True # This runs the preprocessing for training the model
  RUN_TRAINING_DISEASE_CHARACTERIZATION: True 

  
