neo4j_credentials:
  NEO4J_URI: bolt://192.168.1.146:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password
  NEO4J_DB: neo4j

shepherd:
  OVERWRITE_PREPROCESSED_DATA: True # If True, the patients data will be pulled from the neo4j database
  LIMIT_SAMPLE_SIZE: True 
  NUMBER_OF_SAMPLES_LIMIT: 10
  ONLY_PATIENTS_WITH_DISEASE: False # If True, only patients with disease will be used. If during mapping from DOID to MONDO, no diseases are found, the patient will be excluded.

  CREATE_SPL_MATRIX: True # This is necessary if the algo is run on new data

  # this runs the predictions
  RUN_PATIENTS_LIKE_ME: True
  RUN_CAUSAL_GENE_DISCOVERY: True
  RUN_DISEASE_CATEGORIZATION: True

  PATIENTS_AGGR_NODES: phenotypes # Options: phenotypes, phenotypes_and_genes - for patients like me and disease categorization the aggregation for the patient embedding can be changed


  RUN_PREPROCESSING: False # This runs the preprocessing for training the model
  RUN_TRAINING_DISEASE_CHARACTERIZATION: False 
