hparams:
  add_cand_diseases: false
  add_similar_patients: true
  alpha: 0.9
  attention_type: bilinear
  backwards_compatible_loading: false
  batch_size: 64
  candidate_disease_type: orphanet
  checkpoint_path: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - ema30
  - zaklab
  - rare_disease_dx
  - checkpoints
  - patient_NCA
  - 04_26_22:17:38:30_lr_5e-05_val_simulated_pats.disease_split_val_sim_pats_kg_8.9.21_kg_losstype_patient_patient_NCA
  combined_training: true
  debug: false
  decoder_type: bilinear
  filter_edges: false
  freeze_node_embeds: false
  gradclip: 1.0
  inference_batch_size: 512
  kappa: 0.09000000000000001
  lambda: 0.7
  leaky_relu: 0.1
  log_gpu_memory: true
  loss: patient_patient_NCA
  lr: 5.0e-05
  margin: 0.4
  max_epochs: 100
  model_type: patient_NCA
  mrr_vs_percent_overlap: false
  n_cand_diseases: 1000
  n_gpus: 1
  n_similar_patients: 2
  neg_weight: 20
  neighbor_sampler_sizes:
  - 15
  - 10
  - 5
  num_workers: 4
  only_hard_distractors: false
  patient_similarity_type: gene
  pin_memory: false
  plot_PG_embed: false
  plot_attn_nhops: false
  plot_degree_rank: false
  plot_disease_embed: false
  plot_frac_rank: false
  plot_gradients: false
  plot_intrain: false
  plot_nhops_rank: false
  plot_patient_embed: true
  plot_phen_gene_sims: true
  pos_weight: 1
  precision: 16
  profiler: simple
  reload_dataloaders_every_n_epochs: 0
  run_name: 04_26_22:17:38:30_lr_5e-05_val_simulated_pats.disease_split_val_sim_pats_kg_8.9.21_kg_losstype_patient_patient_NCA
  sample_edges_from_train_patients: false
  sample_from_gpd: true
  saved_checkpoint_path: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - ema30
  - zaklab
  - rare_disease_dx
  - kg_embeddings
  - bilinear_tanh_triKG_gatv2_hparamfix
  - checkpoints
  - 10:05:53_run_epoch=171.ckpt
  seed: 33
  softmax_scale: 1
  sparse_sample: 300
  spl: simulated_patients/disease_split_all_sim_patients_kg_8.9.21_kg_spl_matrix.npy
  spl_gate: false
  spl_index: simulated_patients/disease_split_all_sim_patients_kg_8.9.21_kg_spl_index_dict.pkl
  spl_pca: null
  test_data: simulated_patients/disease_split_val_sim_patients_kg_8.9.21_kg.txt
  test_n_cand_diseases: 200
  thresh: 1
  time: false
  train_data: simulated_patients/disease_split_traintest_sim_patients_kg_8.9.21_kg.txt
  train_from_scratch: false
  upsample_cand: 1
  use_diseases: false
  validation_data: simulated_patients/disease_split_val_sim_patients_kg_8.9.21_kg.txt
  wandb_project_name: patients-like-me
  wandb_save_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - ema30
  - zaklab
  - rare_disease_dx
  - wandb
